title: Mary Holtz Art
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hary Holtz Art with new show of alcohol ink art this March 2023.
# baseurl: "/"
url: "www.mary-holtz-art-forestyard.netlify.app" # the base hostname & protocol for your site, e.g. http://example.com

permalink: pretty

collections:
  feed-products:
    output: true
    permalink: "/feed/:path/"
  pages:
    output: true
    permalink: "/:path/"

# Build settings
markdown: kramdown
# theme: minima
gems:
  - jekyll-menus
  - jekyll-babel
exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed

google_analytics: G-MQ5G0ZFSVX 

include: [/faq.md]
exclude: [node_modules]
